name: Python application

on: [push]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.8]
        poetry-version: [1.3.2]

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install poetry and dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install poetry==${{ matrix.poetry-version }} poetry-core==${{ matrix.poetry-version }}
        python -m pip install --no-cache-dir django gunicorn psycopg2-binary

    - name: Configure poetry
      run: |
        poetry config virtualenvs.create false
        poetry config installer.parallel true

    - name: Install project dependencies
      run: |
        poetry install --no-interaction --no-root

    - name: Test
      run: |
        poetry run python manage.py test

    - name: Install Flyctl
      if: github.ref == 'refs/heads/main'
      uses: superfly/flyctl-actions/setup-flyctl@master

    - name: Deploy to Fly.io
      if: github.ref == 'refs/heads/main'
      env:
        FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
      run: flyctl deploy --remote-only