name: Python application

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Cache Poetry
      uses: actions/cache@v2
      with:
        path: ~/.cache/pypoetry
        key: ${{ runner.os }}-poetry-${{ hashFiles('**/poetry.lock') }}
        restore-keys: |
          ${{ runner.os }}-poetry-

    - name: Install and configure Poetry
      run: |
        curl -sSL https://install.python-poetry.org | python3 - --version 1.4.0
        poetry config virtualenvs.create false

    - name: Install Dependencies
      run: |
        poetry install --no-interaction

    - name: Run Tests
      run: |
        poetry run python manage.py test

    - name: Install Flyctl
      if: github.ref == 'refs/heads/main'
      uses: superfly/flyctl-actions/setup-flyctl@master

    - name: Deploy to Fly.io
      if: github.ref == 'refs/heads/main'
      env:
        FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
      run: flyctl deploy --remote-only