name: Python application

on:
  push:
    branches:
      - main  # Executar apenas quando houver push para a branch main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.8]  # Versão do Python a ser utilizada
        poetry-version: [1.5.1]  # Versão específica do Poetry

    steps:
      - name: Checkout código
        uses: actions/checkout@v2

      - name: Configurar Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Instalar Poetry
        run: |
          python -m pip install --upgrade pip
          python -m pip install poetry==1.5.1
          echo "export PATH=$HOME/.local/bin:$PATH" >> $GITHUB_ENV

      - name: Configurar Poetry
        run: |
          poetry config virtualenvs.create false
          poetry config installer.parallel true

      - name: Instalar dependências do projeto
        run: |
          poetry install --no-interaction --no-root

      - name: Executar testes
        run: |
          poetry run python manage.py test

      - name: Instalar Flyctl
        if: github.ref == 'refs/heads/main'
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Deploy para Fly.io
        if: github.ref == 'refs/heads/main'
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        run: flyctl deploy --remote-only
