name: Deploy to Fly.io
on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: 1.5.1

      - name: Install dependencies
        run: poetry install

      - name: Run linting
        run: |
          poetry run flake8 .
          poetry run black . --check

      - name: Run tests with coverage
        run: |
          poetry run coverage run -m pytest
          poetry run coverage report

      - name: Install Flyctl
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Deploy to Fly.io
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        run: flyctl deploy --remote-only

      - name: Health check
        run: |
          sleep 30  # Espera a aplicação iniciar
          curl https://ebac-bookstore-api.fly.dev/health/ 